### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by codingrogue** [richsage/RMSPushNotificationsBundle#103]
Please update the documentation. In the introduction it doesn't even say that windows phone is supported, I found out accidently by reading the config and issues. Also more examples would be very helpful, especially on how to send custom payload via pushes.

**Comment by richsage** [comment]
@codingrogue pull requests are always accepted :-) I'll add a note about the Windows Phone Toast support.

**Comment by codingrogue** [comment]
Okay :)
