### ISSUE TITLE
Missing argument 8 for AppleNotification::__construct()

### ISSUE THREAD

**Issue by Morisf** [richsage/RMSPushNotificationsBundle#104]
Hi,
I've got this issue after setup by readme.
SF - 2.6.*

Warning: Missing argument 8 for RMS\PushNotificationsBundle\Service\OS\AppleNotification::__construct(), called in app/cache/dev/appDevDebugProjectContainer.php on line 3189 and defined

**Comment by richsage** [comment]
@Morisf can you check and see if PR #105 fixes this for you?

**Comment by Morisf** [comment]
@richsage - yes, it's work

**Comment by richsage** [comment]
Thanks - have merged, will tag a new release shortly.
