### ISSUE TITLE
AppleNotification constructor Catchable Fatal Error

### ISSUE THREAD

**Issue by endikamontejo** [richsage/RMSPushNotificationsBundle#108]
Hi!
After updating the symfony I have found out that even with your last rms-push-notification-bundle v0.1.8 I am getting the following error:

Catchable Fatal Error: Argument 7 passed to RMS\\PushNotificationsBundle\\Service\\OS\\AppleNotification::__construct() must be an instance of RMS\\PushNotificationsBundle\\Service\\EventListener, instance of Symfony\\Bridge\\Monolog\\Logger given, called in /Users/xxxxxxx/app/cache/dev/appDevDebugProjectContainer.php on line 2518 and defined

In case it helps, I am using Symfony 2.6

**Comment by richsage** [comment]
Apologies - yes, I've just seen that. Will get a fix out today.

**Comment by endikamontejo** [comment]
Hi! One question. When do you plan to launch a new release with this issue fixed?

**Comment by richsage** [comment]
@endikamontejo can you see #110 and see if this fixes your issue?

**Comment by endikamontejo** [comment]
Hi! Yes, apparently it fixes the issue

**Comment by hobbysoldat** [comment]
Had the same issue. Yes, the fix works.

**Comment by endikamontejo** [comment]
Any release date to have this bug fixed?

**Comment by richsage** [comment]
Released in 0.1.9 :-)
