### ISSUE TITLE
IOS Push Notifications for multiple Apps from one server

### ISSUE THREAD

**Issue by gaph** [richsage/RMSPushNotificationsBundle#113]
I am sending pushNotifications to multiple apps from one server. I am using setAPNSPemAsString method which pick right certificate. But push notification is sent only first time. Can anyone tell me why? Thank you! 

    public function sendIOS($appName){
        $notifications = $this->container->get('rms_push_notifications');

        $message = new iOSMessage();
        $message->setMessage($this->message);
        $message->setData($this->getData());
        $message->setAPSSound("default");
        $message->setDeviceIdentifier($this->pushToken);

        if ($appName !="appName") {
            $pemFile    = $this->container->getParameter("rms_push_notifications.ios.".$appName.".pem");
            $passphrase = $this->container->getParameter("rms_push_notifications.ios.".$appName.".passphrase");

                $pemContent = file_get_contents($pemFile);
                $notifications->setAPNSPemAsString($pemContent, $passphrase);
        }
        return $notifications->send($message);
    }

**Comment by andreichirkunovgoon** [comment]
Did you manage to fix the problem?

**Comment by gaph** [comment]
Yes, thank you.
