### ISSUE TITLE
Unable to assign category

### ISSUE THREAD

**Issue by jorj1** [richsage/RMSPushNotificationsBundle#117]
Seems that setting the category to the "aps" dictionary has been forgotten. It is (should be) as simple as setting the other aps key like badge, sound and content-available.

**Comment by richsage** [comment]
This is [already present](https://github.com/richsage/RMSPushNotificationsBundle/blob/master/Message/AppleMessage.php#L219-L222) - see the `setCategory` method on an `AppleMessage` (eg iOS):
