### ISSUE TITLE
Version 0.2.0

### ISSUE THREAD

**Issue by TheFox** [richsage/RMSPushNotificationsBundle#122]
When will version 0.2.0 be released?

**Comment by richsage** [comment]
Later today :-)

**Comment by TheFox** [comment]
I'm waiting for it. ;)
But seriously, using `dev-master` (especially in Production) is a bad thing.

**Comment by richsage** [comment]
This has just been released :-)

**Comment by richsage** [comment]
Ah - use 0.2.1 now (0.2.0 is broken)

**Comment by TheFox** [comment]
Nice! Thank you. :)
