### ISSUE TITLE
Configuration in README.md

### ISSUE THREAD

**Issue by ngydat** [richsage/RMSPushNotificationsBundle#128]
Hi

I'm doing my internship right now and I've been asked to develop a mobile application based on a website the company is developing with symfony. One of the things they asked me to do is to handle the notifications of the website. But I'm a beginner in symfony so I'm asking all of you : where do I have to put the lines of code from the configuration section ?

Thank you in advance

**Comment by richsage** [comment]
You should take a look at the [Symfony configuration documentation](http://symfony.com/doc/current/book/configuration.html) - the config should go in the appropriate file here.
