### ISSUE TITLE
Bundle maintained and manage Firebase message

### ISSUE THREAD

**Issue by dbuton** [richsage/RMSPushNotificationsBundle#156]
Is the bundle maintained?
And can we send push notification with Firebase with this bundle?

I saw a pull request but not merged yet.

**Comment by richsage** [comment]
Yes - it is maintained albeit slowly. There is one outstanding change on #141

**Comment by dbuton** [comment]
Thanks a lot.
I saw the Pull request, but why is it not merged?

**Comment by richsage** [comment]
There is one outstanding change that needs to be made. Once this is done, I'm happy to merge & release

**Comment by dbuton** [comment]
ok, thanks a lot for your reactivity.
