### ISSUE TITLE
GCM Android working randomly on production

### ISSUE THREAD

**Issue by Kaz-** [richsage/RMSPushNotificationsBundle#66]
Hi ! 
My script sending Android notifications works perfectly on my dev server, and when I'm migrating it to production, it works like 1 times on 20, the other times : 
```php
 $this->container->get('rms_push_notifications')->send($push)
```
is returning false ...

I think it's not related to my GCM or bundle configuration, because it's exactly the same on dev server, and it works perfectly...

CURL is installed and php5-curl too, and I've tried both false and true on 'use_multi_curl' ...

I'm stuck, please help.

**Comment by richsage** [comment]
Configuring timeouts is a PR open at #84 - any feedback welcome!
