### ISSUE TITLE
Sending to Android GCM not working when timeout greather than 5 sec

### ISSUE THREAD

**Issue by andrewsmm** [richsage/RMSPushNotificationsBundle#80]
I have a problem when trying to send push to android by gcm. Problem resolve when i set timeout 15 or 30 sec in /vendor/kriswallsmith/buzz/lib/Buzz/Client/AbstractClient.php

**Comment by emiliomg** [comment]
Same problem here. My application runs in a vagrant environment, and 5 seconds seems to be just a little too short. If I set it to 6 seconds it works.
It would be great to be able to make this parameter configurable.
