### ISSUE TITLE
request timeout when sending iOS push notif

### ISSUE THREAD

**Issue by snjegov** [richsage/RMSPushNotificationsBundle#86]
Hi
My API handles request that fire push notifications to iOS. Sometimes these notification arrive, but sometimes the API request timeouts because of sending notifications.

Does anyone have similiar experience?

**Comment by snjegov** [comment]
i see now that the timeout of 5 sec is the value from kriswallsmith/Buzz lib.
is it possible to override this in symfony? (the file is not the part of a bundle)

**Comment by richsage** [comment]
@snjegov see #84 - if you're able to test this as well and verify things work for you, I'll get it merged and then release.

**Comment by richsage** [comment]
Closing also as duplicate of #80 essentially, and should be resolved by #84. @snjegov if you could confirm your test results on #84 that would be great.
