### ISSUE TITLE
the AppleNotifications service should handle the case of connection closed by the APNS server

### ISSUE THREAD

**Issue by stof** [richsage/RMSPushNotificationsBundle#91]
In case the server closes the connection, a subsequent notification will receive an error with code 10 (``Shutdown``). However, the AppleNotifications service does not handle it and it will continue to reuse the existing stream. This is broken. It should close the corresponding stream and reopen it to initiate a new connection.

**Comment by richsage** [comment]
This looks to be resolved in #101

**Comment by stof** [comment]
yeah exactlty (@tgallice works in my team)
