### ISSUE TITLE
Documentation issue?

### ISSUE THREAD

**Issue by alexdrupal** [richsage/RMSPushNotificationsBundle#97]
HI

Thanks for your nice bundle! Nice work.
I have a question. In the documentation we have:
```php
$message = new iOSMessage();
        $message->setMessage('Oh my! A push notification!');
        $message->setDeviceIdentifier('test012fasdf482asdfd63f6d7bc6d4293aedd5fb448fe505eb4asdfef8595a7');
```
But what about device token? I think Apple's APNS Push is working with device tokens which is different from device ID. Should I pass it into the setDeviceIdentifier or it should be another call?
Let me know.
Thank you.

**Comment by richsage** [comment]
No - you should be able to use `setDeviceIdentifier` with whatever token you've been issued by APN here :-)
